import subprocess
COMMUNICATION_MANAGER_WINDOW_ID = -1
INTEGRATOR_WINDOW_ID = -1
PAUSE_HOOK = True
IS_COMMUNICATION_MANAGER_STARTED = False
LOG = False
BASE_URL = ""

USERNAME = ""
USERID = -1
PROJECT_ID = -1
USER_TOKEN = ""
