/**
 * Schema definition for the Projects collection.
 */

import passwordHash from "password-hash";
import { Schema } from "mongoose";
import { Models } from "../../utils/constants";


const UserSchema = Schema({
    username: {
        type: String,
        required: true,
        maxlength: 50
    },
    // A string containing hash algo, salt and the hashed salted password
    //  as generated by the password-hash module.
    password: {
        type: String,
        required: true,
        minlength: 64,
        maxlength: 100,
        validate: {
            validator: passwordHash.isHashed
        }
    },
    email: {
        type: String,
        required: true,
        maxlength: 32
    }
});

export default UserSchema;